### ISSUE TITLE
Auteurs veld 

### ISSUE THREAD

**Issue by Ayseay** [ahs-mediatheken/bo-main#1]
Vraag van Robin om een veld "Auteur" op te nemen in de beschrijvingen van de B/O.
Dit om een correcte invoer van e-publicaties, juiste APA

**Comment by danydhondt** [comment]
Veld auteurs is toegevoegd aan de e_publicaties.
Gelieve eens na te gaan welke andere input velden er eventueel nog nodig zijn om de apa correct te maken.
